#!/bin/bash -l
#SBATCH --job-name=HWPC_names
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1

module load perftools-base
module load perftools

srun papi_native_avail
srun papi_avail
