#!/bin/bash -l
#SBATCH --job-name=PERF_ADI_AVX_ALIGNED
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running PERF_ADI_AVX_ALIGNED Simulations
echo  

srun $PROJ/ADI_AVX_aligned.exe 1 8 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 16 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 32 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 64 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 120 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 240 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 480 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 960 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 1920 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 3840 0.000000001 10 1000
srun $PROJ/ADI_AVX_aligned.exe 1 7680 0.0000000001 10 1000
