#!/bin/bash -l
#SBATCH --job-name=ADI_OMP_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=3:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=11
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=10
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=9
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=8
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=7
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=6
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=5
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=4
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=3
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=2
srun ./ADI_omp.exe 1 98 0.0000005
export OMP_NUM_THREADS=1
srun ./ADI_omp.exe 1 98 0.0000005