#!/bin/bash -l
#SBATCH --job-name=ADI_OMP_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=3:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=2
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun ./ADI_omp_scalar_original8.exe 1 98 0.0000005
srun ./ADI_omp_scalar_transposed8.exe 1 98 0.0000005
export OMP_NUM_THREADS=1
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun ./ADI_omp_AVX_original8.exe 1 98 0.0000005
srun ./ADI_omp_AVX_transposed4.exe 1 98 0.0000005
srun ./ADI_omp_AVX_transposed8.exe 1 98 0.0000005
srun ./ADI_omp_scalar_original8.exe 1 98 0.0000005
srun ./ADI_omp_scalar_transposed8.exe 1 98 0.0000005
