#!/bin/bash -l
#SBATCH --job-name=ADI_SCALAR_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./ADI_scalar_original8.exe 1 32 0.00001
srun ./ADI_scalar_transposed8.exe 1 32 0.00001
srun ./ADI_scalar_original8.exe 1 82 0.000001
srun ./ADI_scalar_transposed8.exe 1 82 0.000001
srun ./ADI_scalar_original8.exe 1 98 0.0000005
srun ./ADI_scalar_transposed8.exe 1 98 0.0000005
