#!/bin/bash -l
#SBATCH --job-name=ADI_COMPACT_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=6:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export KMP_AFFINITY=compact
echo Affinity = compact
echo
export OMP_NUM_THREADS=12
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
export OMP_NUM_THREADS=6
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
export OMP_NUM_THREADS=4
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
export OMP_NUM_THREADS=3
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
export OMP_NUM_THREADS=2
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
export OMP_NUM_THREADS=1
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
./ADI_omp_combined.exe 1 98 0.0000005 100
./ADI_omp_combined_all.exe 1 98 0.0000005 100
./ADI_omp_separate.exe 1 98 0.0000005 100
./ADI_omp_separate_all.exe 1 98 0.0000005 100
