#!/bin/bash -l
#SBATCH --job-name=ADI_SCALAR_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./ADI_scalar.exe 1 32 0.00001
srun ./ADI_scalar.exe 1 64 0.000001
