#!/bin/bash -l
#SBATCH --job-name=ADI_WEAK_SCALING_2
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running ADI Weak Scaling 2 Simulations
echo  

export KMP_AFFINITY=scatter

export OMP_NUM_THREADS=1
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 2216 0.0000000001 10 1000

export OMP_NUM_THREADS=2
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 3136 0.0000000001 10 1000

export OMP_NUM_THREADS=4
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 4432 0.0000000001 10 1000

export OMP_NUM_THREADS=6
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 5432 0.0000000001 10 1000

export OMP_NUM_THREADS=8
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 6272 0.0000000001 10 1000

export OMP_NUM_THREADS=10
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 7008 0.0000000001 10 1000

export OMP_NUM_THREADS=12
echo OMP_NUM_THREADS = $OMP_NUM_THREADS
srun $PROJ/ADI_omp.exe 1 7680 0.0000000001 10 1000
