#!/bin/bash -l
#SBATCH --job-name=OVS_RW_M
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running OVS_RW_M Simulations
echo  

srun $PROJ/RW_serial.exe 1 32 300 0.00001
srun $PROJ/RW_serial.exe 1 32 1000 0.00001
srun $PROJ/RW_serial.exe 1 32 3000 0.00001
srun $PROJ/RW_serial.exe 1 32 10000 0.00001
srun $PROJ/RW_serial.exe 1 32 30000 0.00001
srun $PROJ/RW_serial.exe 1 32 100000 0.00001
srun $PROJ/RW_serial.exe 1 32 300000 0.00001
srun $PROJ/RW_serial.exe 1 32 1000000 0.00001
srun $PROJ/RW_serial.exe 1 32 3000000 0.00001
srun $PROJ/RW_serial.exe 1 32 10000000 0.00001
srun $PROJ/RW_serial.exe 1 32 30000000 0.00001
srun $PROJ/RW_serial.exe 1 32 100000000 0.00001
srun $PROJ/RW_serial.exe 1 32 300000000 0.00001
srun $PROJ/RW_serial.exe 1 32 1000000000 0.00001
srun $PROJ/RW_serial.exe 1 32 3000000000 0.00001
