#!/bin/bash -l
#SBATCH --job-name=PERF_RW_SERIAL_3
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running PERF_RW_SERIAL_3 Simulations
echo  

srun $PROJ/RW_serial.exe 1 242 58564000 0.000000001 1 50
