#!/bin/bash -l
#SBATCH --job-name=RW_AVX_TEST
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun Project/RW_AVX_backup.exe 1 98 1000000 0.00001 20
srun Project/RW_AVX.exe 1 98 1000000 0.00001 20
srun Project/RW_AVX_backup.exe 1 50 1000000 0.00001 20
srun Project/RW_AVX.exe 1 50 1000000 0.00001 20
