#!/bin/bash -l
#SBATCH --job-name=PAT_ADI_SCALAR_2
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running PAT_ADI_SCALAR_2 Simulations
echo  

export PAT_RT_CALLSTACK=0
export PAT_RT_TRACE_FUNCTION_ARGS=0
export PAT_RT_PERFCTR="PAPI_TOT_CYC,PAPI_L3_TCM,PAPI_L2_TCM,PAPI_L1_TCM"

srun $PROJ/ADI_pat_scalar.exe 1 7682 0.0000000001 10 1000
