#!/bin/bash -l
#SBATCH --job-name=PERF_ADI_SERIAL
#SBATCH --mail-user=maloneys@student.ethz.ch
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
echo Running PERF_ADI_SERIAL Simulations
echo  

srun $PROJ/ADI_serial.exe 1 10 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 18 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 34 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 66 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 122 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 242 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 482 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 962 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 1922 0.000000001 10 1000
srun $PROJ/ADI_serial.exe 1 3842 0.000000001 10 1000
